language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  #- "2.6"
  - "2.7"

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      export CONDA_OS=MacOSX
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update
      export CONDA_OS=Linux
    fi

install:
  - bash script/conda_build.sh

script:
  - mkdir menace_test && cd menace_test && menace -e hedani@chalmers.se test && cd ..

after_success:
  - bash script/conda_upload.sh