language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  #- "2.6"
  - "2.7"

os:
  - linux
  - osx

before_install:
  - bash script/conda_preinstall.sh

install:
  - bash script/conda_build.sh

script:
  - mkdir menace_test && cd menace_test && menace -e hedani@chalmers.se test && cd ..

after_success:
  - bash script/conda_upload.sh