#!/usr/bin/env bash
#SBATCH -A $PROJECTID
#SBATCH -p $CLUSTER
#SBATCH -J $RUNNAME 
#SBATCH -N 1
#SBATCH -n $CPUCORES
#SBATCH -t 4:00:00
#SBATCH -o output.%A_%a.stdout
#SBATCH -e output.%A_%a.stderr
#SBATCH --mail-type=END
#SBATCH --mail-user=$EMAIL

source $SLURM_SUBMIT_DIR/loadmodules.sh
source $SLURM_SUBMIT_DIR/config.sh

mkdir $TMPDIR/Data
mkdir $TMPDIR/Analysis
mkdir $TMPDIR/RefSeq/
mkdir $TMPDIR/RefSeq/Index
mkdir $TMPDIR/RefSeq/Headers
mkdir $TMPDIR/DoriC

STARTIND=$[$START_IND+$SLURM_ARRAY_TASK_ID*5]

seq $STARTIND $[$STARTIND+4] | parallel cp $DATA_PATH/$FOLDER_PREFIX{}/* $TMPDIR/Data

pdcp -r $REF_PATH $TMPDIR
pdcp -r $DORIC_PATH $TMPDIR

$SUBMIT_DIR/mainBuild.sh $SUBMIT_DIR $REF_NAME

mkdir $OUT_PATH/$RUN_NAME

rpdcp -r $TMPDIR/Data $OUT_PATH/$RUN_NAME

# End script
