{% set name = "menace" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: True # [osx]
  #number: 2
  #string: boost{{CONDA_BOOST}}_{{PKG_BUILDNUM}}

source:
  git_rev: {{ version }}
  git_url: https://github.com/zertan/Menace.git
  #fn: v{{ version }}.tar.gz
  #url: https://github.com/zertan/Menace/archive/{{ version }}.tar.gz
  #md5: 596c56a476b26a294b46e6e36890c136

requirements:
  build:
  #- gcc # [not osx]
  #- llvm # [osx]
  #- boost {{CONDA_BOOST}}*
  #- google-sparsehash
  #- sqlite
  #- openmpi 

  run:
  - bowtie2
  - samtools
  - bamtools
  - parallel
  #- bwa
  #- libgcc # [not osx]
  #- pandoc
  #- sqlite
  #- openmpi

test:
  commands:
    - menace -v

about:
  home: http://www.github.com/SysBioChalmers/Menace
  license: MIT
  license_file: LICENSE
  summary: Menace -- A metagenomics pipeline for estimation of relative cell periods
