#!/usr/bin/env bash
#SBATCH -A {{ project }}
#SBATCH -p {{ cluster }}
#SBATCH -J {{ job_name }} 
#SBATCH -N {{ job_nodes}}
#SBATCH -n {{ cpu_cores }}
#SBATCH -t {{ estimated_time }}
#SBATCH -o output.%A_%a.stdout
#SBATCH -e output.%A_%a.stderr
#SBATCH --mail-type=END
#SBATCH --mail-user={{ email }}

source $SLURM_SUBMIT_DIR/bin/loadmodules.sh

NODE_PATH={{ node_path }}
REF_PATH={{ ref_path }}
DATA_PATH={{ data_path }}
OUTPUT_PATH={{ output_path }}

REF_NAME={{ ref_name }}
START_IND={{ start_ind }}
SAMPLES_PER_NODE={{ samples_per_node }}
CPU_CORES={{ cpu_cores }}

DATA_PREFIX={{ data_prefix }}

mkdir $NODE_PATH/Data
mkdir $NODE_PATH/Analysis
mkdir $NODE_PATH/References
mkdir $NODE_PATH/References/Index
mkdir $NODE_PATH/References/Headers
mkdir $NODE_PATH/DoriC

IND=$[$START_IND+$SLURM_ARRAY_TASK_ID*$SAMPLES_PER_NODE]

seq $IND $[$IND+$SAMPLES_PER_NODE-1] | parallel cp $DATA_PATH/$DATA_PREFIX{}* $NODE_PATH/Data

pdcp -r $REF_PATH/Headers $NODE_PATH/References
pdcp -r $REF_PATH/Index $NODE_PATH/References
pdcp $REF_PATH/taxIDs.txt $NODE_PATH/References

pdcp $DORIC_PATH/* $NODE_PATH/DoriC

$SLURM_SUBMIT_DIR/bin/mainBuild.sh $SLURM_SUBMIT_DIR $REF_NAME $CPU_CORES $NODE_PATH

mkdir -p $OUTPUT_PATH

rpdcp -r $NODE_PATH/Data $OUTPUT_PATH

# End script
